kind: Kustomization
#- ingress.yaml
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- secret.yaml
namespace: fidelite
images:
- name: nexus.labelvie.ma:8012/ma-lbv-fidelite-frontend
  newTag: "5806"
apiVersion: kustomize.config.k8s.io/v1beta1
